name: Build and produce artifacts

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Pull csswg-drafts
      run: git submodule update --init
    
    - name: Install bikeshed
      run: |
        python -m pip install bikeshed
        python -m bikeshed update

    - name: Generate build/
      run: make
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        path: build
